_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    NAME: "CommonalityROIHeads"
    OUTPUT_LAYER: "DoubleFastRCNNOutputLayers"
    MEMORY: True
    AUGMENTATION: True
    SEMANTIC: True
    WARMUP_DISTILL: 200
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("removevoc_2007_trainval_allx_3shot_seedx", )
  TEST: ('voc_2007_test_allx',)
  TWO_STREAM: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (1000,)
  MAX_ITER: 1200
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
  EVAL_PERIOD: 20000
OUTPUT_DIR: "/Path/to/Output/Dir"
SEED: 23